services:
  vz-server:
    build: ./server
    # command: npm start
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/server-app/src
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: http --subdomain=tseki 3001
    network_mode: "host"
